[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.build]
cmds = ["pip install --no-cache-dir --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "uvicorn main_web:app --host 0.0.0.0 --port $PORT"
